In [1]:
import torch.nn as nn
import torch

# torch.nn.Conv2d(in_channels, 
#                 out_channels, 
#                 kernel_size, 
#                 stride=1, 
#                 padding=0, 
#                 dilation=1, 
#                 groups=1, 
#                 bias=True, 
#                 padding_mode='zeros', 
#                 device=None, 
#                 dtype=None)

In [3]:
test = torch.randn(2,3,32,32)
x = torch.tensor([[-2, 1, 2, 6, 4], [-3, 1, 7, 2, -2], [-4, 2, 3, -1 , -3], [-7, 1, 2, 3, 11], [5, -7, 8, 12, -9]]).float()
x = x.unsqueeze(0)

y_1 = nn.MaxPool2d(kernel_size=2,stride=2, padding=0)
y_2 = nn.MaxPool2d(kernel_size=2,stride=2, padding=0, ceil_mode=True)
print(x)
print(y_1(x))
print(y_2(x))

tensor([[[-2.,  1.,  2.,  6.,  4.],
         [-3.,  1.,  7.,  2., -2.],
         [-4.,  2.,  3., -1., -3.],
         [-7.,  1.,  2.,  3., 11.],
         [ 5., -7.,  8., 12., -9.]]])
tensor([[[1., 7.],
         [2., 3.]]])
tensor([[[ 1.,  7.,  4.],
         [ 2.,  3., 11.],
         [ 5., 12., -9.]]])


In [24]:
# With square kernels and equal stride

# non-square kernels and unequal stride and with padding
conv1_1 = nn.Conv2d(3, 64, 3, 1, 1)
conv1_2 = nn.Conv2d(64, 64, 3, 1, 1)
pool1 = nn.MaxPool2d(2, stride=2, ceil_mode=True) #1/2
input = torch.randn(10 ,3, 224, 224)
print('input',input.size())
a1=conv1_1(input)
print('a1',a1.size())
a2=conv1_2(a1)
print('a2',a2.size())
a3 = pool1(a2)
print('a3',a3.size())

input torch.Size([10, 3, 224, 224])
a1 torch.Size([10, 64, 224, 224])
a2 torch.Size([10, 64, 224, 224])
a3 torch.Size([10, 64, 112, 112])
